[font]
size = 10

[window]
opacity = 0.8
padding = { x = 20, y = 20 }
dynamic_padding = true
decorations =  "None"
startup_mode = "Maximized"

[shell]
program = "/bin/tmux"

[env]
EDITOR = "/bin/nvim"
